### ISSUE TITLE
Code does not support the openapi "Tags" feature

### ISSUE THREAD

**Issue by Jeff-Lowrey** [Jeff-Lowrey/openapi-client#1]
When I try to use this extension to work with an OpenAPI document version 3.0.3

It produces 

```
simple_openapi_client\parser.py", line 20, in parse_openapi
    return Document(**content)
           ^^^^^^^^^^^^^^^^^^^s
TypeError: Document.__init__() got an unexpected keyword argument 'tags'

```

**Example**
```  
"tags": [
    {
      "name": "XYZ API",
      "description": "API operations for the XYZ System."
    },
    {
      "name": "PDQ",
      "description": "API operations the PDQ System."
    }
  ],
  "paths": {
...  
```
